### PR TITLE
Fix WaitForAvailableCinderVolume() to polling

### LINKED ISSUE #427: WaitForAvailableCinderVolume only sleep 5 seconds instead of polling until volume in available
https://github.com/kubernetes-incubator/external-storage/blob/master/openstack/standalone-cinder/pkg/volumeservice/actions.go#L110-L117

### PR DESCRIPTION
**Pull request by chestack**
This PR fix function WaitForAvailableCinderVolume() to polling check volume status, get volume every 3 seconds and up to 10 times

This PR closes #427

### CODE REVIEW

File: openstack/standalone-cinder/pkg/volumeservice/actions.go [hunk 1]
```diff
@@ -108,11 +109,26 @@ func CreateCinderVolume(vs *gophercloud.ServiceClient, options controller.Volume
...
 	c := make(chan error)
-	go time.AfterFunc(5*time.Second, func() {
-		c <- nil
-	})
+	go func() error {
+		num :=0
+		for {
+			time.Sleep(3 * time.Second)
+			if num > 10 {
+				err := errors.New("Failed to get volume status after max retries")
```
Comment (aglitke) [inline openstack/standalone-cinder/pkg/volumeservice/actions.go]: I would prefer at least a pair of constants to define the sleep interval and max retries

File: openstack/standalone-cinder/pkg/volumeservice/actions.go [hunk 2]
```diff
@@ -108,11 +109,26 @@ func CreateCinderVolume(vs *gophercloud.ServiceClient, options controller.Volume
...
+				c <- err
+			}
+			volume, err := volumes_v2.Get(vs, volumeID).Extract()
+			if err != nil {
+				glog.Errorf("Failed to get volume:%v ", volumeID)
```
Comment (aglitke) [inline openstack/standalone-cinder/pkg/volumeservice/actions.go]: This should either skip to the next iteration or bail out as we cannot continue to use the volume object in the next if statement if err != nil.

File: openstack/standalone-cinder/pkg/volumeservice/actions.go (hunk 1 above)
Comment (chestack) [reply openstack/standalone-cinder/pkg/volumeservice/actions.go]: absolutely, I will fix it in next patch

File: openstack/standalone-cinder/pkg/volumeservice/actions.go (hunk 2 above)
Comment (chestack) [reply openstack/standalone-cinder/pkg/volumeservice/actions.go]: agree, change to skip to the next iteration

**Comment by chestack** [comment]
@aglitke , thanks for your comments. I had fixed it. please help review

File: openstack/standalone-cinder/pkg/volumeservice/actions.go [hunk 3]
```diff
@@ -108,11 +111,27 @@ func CreateCinderVolume(vs *gophercloud.ServiceClient, options controller.Volume
...
 	c := make(chan error)
-	go time.AfterFunc(5*time.Second, func() {
-		c <- nil
-	})
+	go func() error {
+		num := 0
+		for {
+			time.Sleep(sleepTime * time.Second)
+			if num > maxRetry {
+				err := errors.New("Failed to get volume status after max retries")
```
Comment (aglitke) [inline openstack/standalone-cinder/pkg/volumeservice/actions.go]: This error would be better written as: "Volume not available after max retries"

File: openstack/standalone-cinder/pkg/volumeservice/actions.go [hunk 4]
```diff
@@ -108,11 +111,27 @@ func CreateCinderVolume(vs *gophercloud.ServiceClient, options controller.Volume
...
+				c <- err
+			}
+			volume, err := volumes_v2.Get(vs, volumeID).Extract()
```
Comment (aglitke) [inline openstack/standalone-cinder/pkg/volumeservice/actions.go]: You might consider adding a vsbroker interface for volumes_v2.Get.   See #453.  We want to add unit tests for this method to ensure that it behaves as expected in the good case, when max retries are exceeded, and when we fail to get the volume information whatsoever.

File: openstack/standalone-cinder/pkg/volumeservice/actions.go (hunk 3 above)
Comment (chestack) [reply openstack/standalone-cinder/pkg/volumeservice/actions.go]: Done in next change

File: openstack/standalone-cinder/pkg/volumeservice/actions.go (hunk 4 above)
Comment (chestack) [reply openstack/standalone-cinder/pkg/volumeservice/actions.go]: Agree that It's better to add interface/function "getCinderVolumeState" into vsbroker/actions,  and reuse it in function "waitForAvailableCinderVolume"(could also be reused in other cases).  But it will be overlap with what did in #453

**Comment by chestack** [comment]
@aglitke , we do not  have UT both for vsbroker.go and actions.go. So should I add UT in this PR or another one?

**Comment by aglitke** [comment]
@chestack No need to test the vsbroker or actions directly.  What I mean is that we should test the provision flow in a few situations where polling for the volume may succeed or fail.  You can test these cases by overriding a new GetVolume interface just like we do for some of the other provisioner tests.

File: openstack/standalone-cinder/pkg/volumeservice/actions.go [hunk 5]
```diff
@@ -108,11 +111,26 @@ func CreateCinderVolume(vs *gophercloud.ServiceClient, options controller.Volume
 // become available.  The connection information cannot be retrieved from cinder
 // until the volume is available.
 func WaitForAvailableCinderVolume(vs *gophercloud.ServiceClient, volumeID string) error {
-	// TODO: Implement proper polling instead of brain-dead timers
 	c := make(chan error)
-	go time.AfterFunc(5*time.Second, func() {
-		c <- nil
-	})
+	go func() error {
```
Comment (wenjun93) [inline openstack/standalone-cinder/pkg/volumeservice/actions.go]: could we use util function `k8s.io/apimachinery/pkg/util/wait.poll()` instead? @chestack @aglitke

Comment (aglitke) [reply openstack/standalone-cinder/pkg/volumeservice/actions.go]: @wenjun93 +1

Comment (hzxuzhonghu) [reply openstack/standalone-cinder/pkg/volumeservice/actions.go]: +1

Comment (chestack) [reply openstack/standalone-cinder/pkg/volumeservice/actions.go]: thanks for all your comments. Done in next patch. sorry for fixing it late.

File: openstack/standalone-cinder/pkg/volumeservice/actions.go [hunk 6]
```diff
@@ -108,12 +111,10 @@ func CreateCinderVolume(vs *gophercloud.ServiceClient, options controller.Volume
 // become available.  The connection information cannot be retrieved from cinder
 // until the volume is available.
 func WaitForAvailableCinderVolume(vs *gophercloud.ServiceClient, volumeID string) error {
-	// TODO: Implement proper polling instead of brain-dead timers
-	c := make(chan error)
-	go time.AfterFunc(5*time.Second, func() {
-		c <- nil
+	return wait.Poll(interval, timeout, func() (bool, error) {
+		status, err := GetCinderVolumeStatus(vs, volumeID)
+		return status == "available", err
```
Comment (rootfs) [inline openstack/standalone-cinder/pkg/volumeservice/actions.go]: i am paranoid but making strings.ToLower() to these strings is more robust

Comment (chestack) [reply openstack/standalone-cinder/pkg/volumeservice/actions.go]: that make sense. Fix it in next change

**Comment by rootfs** [comment]
/lgtm

cc @childsb for merge

**Comment by rootfs** [comment]
@chestack please rebase and ping us when ready for merge

**Comment by chestack** [comment]
@rootfs @childsb , has rebased, please review.
